// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTsoHlvK0k_r94PwUJdL2UMpWTv2Y3Aks',
    appId: '1:1058917940423:web:81f08e14a0349aa21952e2',
    messagingSenderId: '1058917940423',
    projectId: 'algorhymns04',
    authDomain: 'algorhymns04.firebaseapp.com',
    storageBucket: 'algorhymns04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFG_xHPG6pCn48daABbV6SaSZIqrI2UTE',
    appId: '1:1058917940423:android:b262c85f04b707fd1952e2',
    messagingSenderId: '1058917940423',
    projectId: 'algorhymns04',
    storageBucket: 'algorhymns04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMCt6k8HB-UmPsv-kRllU7TTEwYn2LYks',
    appId: '1:1058917940423:ios:e258949f39a576231952e2',
    messagingSenderId: '1058917940423',
    projectId: 'algorhymns04',
    storageBucket: 'algorhymns04.appspot.com',
    iosBundleId: 'com.example.algorhymns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMCt6k8HB-UmPsv-kRllU7TTEwYn2LYks',
    appId: '1:1058917940423:ios:e258949f39a576231952e2',
    messagingSenderId: '1058917940423',
    projectId: 'algorhymns04',
    storageBucket: 'algorhymns04.appspot.com',
    iosBundleId: 'com.example.algorhymns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTsoHlvK0k_r94PwUJdL2UMpWTv2Y3Aks',
    appId: '1:1058917940423:web:56e69389ec1453181952e2',
    messagingSenderId: '1058917940423',
    projectId: 'algorhymns04',
    authDomain: 'algorhymns04.firebaseapp.com',
    storageBucket: 'algorhymns04.appspot.com',
  );

}