// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAqwFXM1vyXF6M38i0SW9FfZ3l9YFZa4o',
    appId: '1:758889243967:web:1296dcb7ecdb9539919f8a',
    messagingSenderId: '758889243967',
    projectId: 'algorhymns-db17e',
    authDomain: 'algorhymns-db17e.firebaseapp.com',
    storageBucket: 'algorhymns-db17e.appspot.com',
    measurementId: 'G-K7WKLJHDDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3N7RHeKidbvNaEu6Zs55_yxM9XoSwU5k',
    appId: '1:758889243967:android:06c1e90210079cce919f8a',
    messagingSenderId: '758889243967',
    projectId: 'algorhymns-db17e',
    storageBucket: 'algorhymns-db17e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7OfyfdkbGkR6yOUfZsE8l9I3oiYSBSLw',
    appId: '1:758889243967:ios:80fc889acfd302bc919f8a',
    messagingSenderId: '758889243967',
    projectId: 'algorhymns-db17e',
    storageBucket: 'algorhymns-db17e.appspot.com',
    iosBundleId: 'com.example.algorhymns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7OfyfdkbGkR6yOUfZsE8l9I3oiYSBSLw',
    appId: '1:758889243967:ios:80fc889acfd302bc919f8a',
    messagingSenderId: '758889243967',
    projectId: 'algorhymns-db17e',
    storageBucket: 'algorhymns-db17e.appspot.com',
    iosBundleId: 'com.example.algorhymns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAqwFXM1vyXF6M38i0SW9FfZ3l9YFZa4o',
    appId: '1:758889243967:web:2ff1d71f5011c3fc919f8a',
    messagingSenderId: '758889243967',
    projectId: 'algorhymns-db17e',
    authDomain: 'algorhymns-db17e.firebaseapp.com',
    storageBucket: 'algorhymns-db17e.appspot.com',
    measurementId: 'G-S6F84SVRDQ',
  );

}