// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm2LZ4FRw3-MTkuB3-ffsl4XkkYtsnQtU',
    appId: '1:314369334122:web:6642f88e24772a296c2313',
    messagingSenderId: '314369334122',
    projectId: 'algorhymns0101',
    authDomain: 'algorhymns0101.firebaseapp.com',
    storageBucket: 'algorhymns0101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRxPEsPOTMG66GYBfU0iwgdgnhFAjaffo',
    appId: '1:314369334122:android:e3129d5567f44e866c2313',
    messagingSenderId: '314369334122',
    projectId: 'algorhymns0101',
    storageBucket: 'algorhymns0101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMaDlWzdsNvw-aWQnmxzr8eqpcHuaQAQM',
    appId: '1:314369334122:ios:3ca49f5122f2513a6c2313',
    messagingSenderId: '314369334122',
    projectId: 'algorhymns0101',
    storageBucket: 'algorhymns0101.appspot.com',
    iosBundleId: 'com.example.algorhymns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMaDlWzdsNvw-aWQnmxzr8eqpcHuaQAQM',
    appId: '1:314369334122:ios:3ca49f5122f2513a6c2313',
    messagingSenderId: '314369334122',
    projectId: 'algorhymns0101',
    storageBucket: 'algorhymns0101.appspot.com',
    iosBundleId: 'com.example.algorhymns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm2LZ4FRw3-MTkuB3-ffsl4XkkYtsnQtU',
    appId: '1:314369334122:web:23e10a16059a4f386c2313',
    messagingSenderId: '314369334122',
    projectId: 'algorhymns0101',
    authDomain: 'algorhymns0101.firebaseapp.com',
    storageBucket: 'algorhymns0101.appspot.com',
  );
}
